### ISSUE TITLE
Weka git @waikato is not responding 

### ISSUE THREAD

**Issue by herpsonc** [Waikato/weka#2]
Hi, 
https://git.cms.waikato.ac.nz/weka/weka is not responding 
Is it a planned service interruption ?

Best.

**Comment by fracpete** [comment]
Not that I'm aware of. Im currently running:

git clone https://git.cms.waikato.ac.nz/weka/weka.git

BTW This is a very large repo (several GB). You might be better off grabbing the src jar that comes with a release or the nightly snapshots.

**Comment by fracpete** [comment]
presumed to be sorted
